---
# [ k3s - tasks/k3s_token.yml ]

- ansible.builtin.wait_for:
    path: "{{ k3s_data_dir }}/server/node-token"
  run_once: true

- ansible.builtin.slurp:
    path: "{{ k3s_data_dir }}/server/node-token"
  register: k3s_server_node_token
  run_once: true

- ansible.builtin.set_fact:
    k3s_token: "{{ k3s_server_node_token.content | b64decode | regex_replace('\n', '') }}"
