---
# [ k3s - tasks/k3s_vip.yml ]

# Create k3s-vip manifest (kube-vip)
- block:
    - name: Create k3s-vip manifest (kube-vip)
      ansible.builtin.command: "ctr images pull {{ (k3s_kube_vip_image != '') | ternary(k3s_kube_vip_image, 'ghcr.io/kube-vip/kube-vip') }}:{{ k3s_kube_vip_version }}"
      changed_when: false

    - ansible.builtin.shell: |
        ctr run --rm --net-host {{ (k3s_kube_vip_image != '') | ternary(k3s_kube_vip_image, 'ghcr.io/kube-vip/kube-vip') }}:{{ k3s_kube_vip_version }} kube-vip-manifests /kube-vip manifest daemonset \
            --interface {{ ansible_default_ipv4.interface }} \
            --address {{ k3s_advertise_address }} \
            --inCluster \
            --taint \
            --controlplane \
            --arp \
            --leaderElection | tee {{ k3s_data_dir }}/server/manifests/kube-vip.yaml
      changed_when: false

    # - lineinfile:
    #     path: "{{ k3s_data_dir }}/server/manifests/kube-vip.yaml"
    #     backrefs: true
    #     regexp: "^(.*image: ).*$"
    #     line: '\1{{ k3s_kube_vip_image }}:{{ k3s_kube_vip_version }}'
    #   when: k3s_kube_vip_image != ""

    - ansible.builtin.get_url:
        url: "https://kube-vip.io/manifests/rbac.yaml"
        dest: "{{ k3s_data_dir }}/server/manifests/kube-vip-rbac.yaml"
        mode: "0600"

  when:
    - k3s_vip_provider == "kube-vip"
    - ansible_play_hosts[0] == inventory_hostname


# Create k3s-vip manifest (keepalived)
- block:
    - name: Create k3s-vip manifest (keepalived)
      ansible.builtin.stat:
        path: "{{ k3s_data_dir }}/server/manifests/k3s-vip-{{ inventory_hostname_short }}.yaml"
      register: k3s_vip_static_pod_manifest_file

    - ansible.builtin.shell: "grep -A1 'KEEPALIVED_PASSWORD' {{ k3s_vip_static_pod_manifest_file.stat.path }} | grep -oP '(?<=\").*(?=\")'"
      changed_when: false
      register: k3s_vip_auth_pass
      check_mode: false
      when:
        - ansible_play_hosts[0] == inventory_hostname
        - k3s_vip_static_pod_manifest_file.stat.exists
        - not (k3s_vip_reset_keepalived_password | bool)

    - ansible.builtin.template:
        src: "manifests/keepalived.yaml.j2"
        dest: "{{ k3s_data_dir }}/server/manifests/k3s-vip-{{ inventory_hostname_short }}.yaml"
        owner: "root"
        group: "root"
        mode: "0600"
      register: k3s_vip_static_pod_manifest

    - ansible.builtin.shell: "grep -A1 'KEEPALIVED_PASSWORD' {{ k3s_vip_static_pod_manifest_file.stat.path }} | grep -oP '(?<=\").*(?=\")'"
      changed_when: false
      register: k3s_vip_auth_pass
      check_mode: false

    # Reload k3s-vip static pod configuration
    - name: Reload k3s-vip static pod configuration
      ansible.builtin.command: kubectl -n kube-system delete pod k3s-vip-{{ inventory_hostname_short }}
      changed_when: false
      failed_when: false
      when:
        - k3s_vip_static_pod_manifest_file.stat.exists
        - k3s_vip_static_pod_manifest.changed

  when: k3s_vip_provider == "keepalived"
