---
# [ k3s - tasks/k3s_private_registry_tls.yml ]

- name: "Check tls files for {{ k3s_private_registry_config.key }}"
  copy:
    dest: "
          {%- if item.key == 'ca_file_content' %}{{ k3s_private_registry_tls.path }}/{{ k3s_private_registry_config.key | regex_replace('-|\\.|:', '_') }}__ca.crt{% endif -%}
          {%- if item.key == 'cert_file_content' %}{{ k3s_private_registry_tls.path }}/{{ k3s_private_registry_config.key | regex_replace('-|\\.|:', '_') }}__cert.crt{% endif -%}
          {%- if item.key == 'key_file_content' %}{{ k3s_private_registry_tls.path }}/{{ k3s_private_registry_config.key | regex_replace('-|\\.|:', '_') }}__cert.key{% endif -%}
          "
    content: "{{ item.value }}"
    mode: 0640
  no_log: yes
  with_items: "{{ k3s_private_registry_config.value.tls | dict2items | rejectattr('key', 'eq', 'insecure_skip_verify') }}"