---
# [ k3s - tasks/k3s_token.yml ]

- wait_for:
    path: "{{ k3s_data_dir }}/server/node-token"
  run_once: yes

- slurp:
    path: "{{ k3s_data_dir }}/server/node-token"
  register: k3s_server_node_token
  run_once: yes

- set_fact:
    k3s_token: "{{ k3s_server_node_token.content | b64decode | regex_replace('\n', '') }}"