---
# [ k3s - tasks/k3s_firewall.yml ]

# Set firewall masquerade
- name: Set firewall masquerade
  firewalld:
    zone: "{{ k3s_firewall_masquerade_zone }}"
    masquerade: '"{{ k3s_firewall_masquerade_enabled }}"'
    permanent: yes
    state: "{{ k3s_firewall_masquerade_enabled | bool | ternary('enabled','disabled') }}"
  notify: Reload firewalld service

- meta: flush_handlers


# K3S server firewall rules
- name: K3S server firewall rules
  firewalld:
    zone: "{{ item.zone | default('public') }}"
    port: "{{ item.port_range }}/{{ item.protocol }}"
    permanent: "{{ item.permanent | default('yes') }}"
    state: "{{ item.state | default('enabled') }}"
  with_items: "{{ (k3s_server_firewall_rules + k3s_firewall_additional_rules) | selectattr('port_range', 'defined') }}"
  notify: Reload firewalld service
  when: "'k3s_server' in group_names"

- firewalld:
    zone: "{{ item.zone | default('public') }}"
    service: "{{ item.service }}"
    permanent: "{{ item.permanent | default('yes') }}"
    state: "{{ item.state | default('enabled') }}"
  with_items: "{{ (k3s_server_firewall_rules + k3s_firewall_additional_rules) | selectattr('service', 'defined') }}"
  notify: Reload firewalld service
  when: "'k3s_server' in group_names"


# K3S agent firewall rules
- name: K3S agent firewall rules
  firewalld:
    zone: "{{ item.zone | default('public') }}"
    port: "{{ item.port_range }}/{{ item.protocol }}"
    permanent: "{{ item.permanent | default('yes') }}"
    state: "{{ item.state | default('enabled') }}"
  with_items: "{{ (k3s_agent_firewall_rules + k3s_firewall_additional_rules) | selectattr('port_range', 'defined') }}"
  notify: Reload firewalld service
  when: "'k3s_agent' in group_names"

- firewalld:
    zone: "{{ item.zone | default('public') }}"
    service: "{{ item.service }}"
    permanent: "{{ item.permanent | default('yes') }}"
    state: "{{ item.state | default('enabled') }}"
  with_items: "{{ (k3s_agent_firewall_rules + k3s_firewall_additional_rules) | selectattr('service', 'defined') }}"
  notify: Reload firewalld service
  when: "'k3s_agent' in group_names"

- meta: flush_handlers