---
# [ k3s - tasks/k3s_kubeconfig.yml ]

- block:
  - file:
      path: "/home/{{ ansible_facts_env_user }}/.kube"
      state: directory
      owner: "{{ ansible_facts_env_user }}"
      group: "{{ ansible_facts_env_user }}"
      mode: "0700"

  - copy:
      src: "{{ k3s_additional_options['write-kubeconfig'] is defined | ternary(k3s_additional_options['write-kubeconfig'], '/etc/rancher/k3s/k3s.yaml') }}"
      dest: "/home/{{ ansible_facts_env_user }}/.kube/config"
      owner: "{{ ansible_facts_env_user }}"
      group: "{{ ansible_facts_env_user }}"
      mode: "0600"
      remote_src: yes


  # Update kubeconfig server address
  - name: Update kubeconfig server address
    shell: "kubectl --kubeconfig /home/{{ ansible_facts_env_user }}/.kube/config config set-cluster default --server=https://{{ (k3s_advertise_address_fqdn != '') | ternary(k3s_advertise_address_fqdn, k3s_advertise_address) }}:{{ k3s_advertise_port }}"
    changed_when: no
    when: k3s_advertise_address != ""
    tags: [ update-k3s_kubeconfig ]


  # Fetch kubeconfig
  - name: Fetch kubeconfig
    fetch:
      src: "/home/{{ ansible_facts_env_user }}/.kube/config"
      dest: "{{ k3s_kubeconfig_local_path }}"
      flat: yes
    changed_when: no
    when: hostvars[groups['k3s_server'][0]].inventory_hostname_short == inventory_hostname_short
    tags: [ update-k3s_kubeconfig, fetch-k3s_kubeconfig ]

  tags: [ install-k3s, copy-k3s_kubeconfig ]