---
# [ k3s - tasks/k3s_kubeconfig.yml ]

- block:
  - ansible.builtin.file:
      path: "/home/{{ ansible_facts_env_user }}/.kube"
      state: directory
      owner: "{{ ansible_facts_env_user }}"
      group: "{{ ansible_facts_env_user }}"
      mode: "0700"

  - ansible.builtin.copy:
      src: "{{ k3s_additional_options['write-kubeconfig'] is defined | ternary(k3s_additional_options['write-kubeconfig'], '/etc/rancher/k3s/k3s.yaml') }}"
      dest: "/home/{{ ansible_facts_env_user }}/.kube/config"
      owner: "{{ ansible_facts_env_user }}"
      group: "{{ ansible_facts_env_user }}"
      mode: "0600"
      remote_src: true
    changed_when: false


  # Update kubeconfig server address
  - name: Update kubeconfig server address
    ansible.builtin.command: "kubectl --kubeconfig /home/{{ ansible_facts_env_user }}/.kube/config config set-cluster default --server=https://{{ (k3s_advertise_address_fqdn != '') | ternary(k3s_advertise_address_fqdn, k3s_advertise_address) }}:{{ k3s_advertise_port }}"
    changed_when: false
    when: k3s_advertise_address != ""
    tags: [ update-k3s_kubeconfig ]


  # Fetch kubeconfig
  - name: Fetch kubeconfig
    ansible.builtin.fetch:
      src: "/home/{{ ansible_facts_env_user }}/.kube/config"
      dest: "{{ k3s_kubeconfig_local_path }}"
      flat: true
    changed_when: false
    when: ansible_play_hosts[0] == inventory_hostname
    tags: [ update-k3s_kubeconfig, fetch-k3s_kubeconfig ]

  tags: [ install-k3s, copy-k3s_kubeconfig ]
