---
# [ k3s - handlers ]

- name: daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart k3s service
  ansible.builtin.systemd:
    name: "{{ k3s_system_name }}"
    enabled: true
    masked: false
    state: restarted
