---
# [ k3s - handlers ]

- name: daemon-reload
  systemd:
    daemon_reload: yes

- name: Restart k3s service
  systemd:
    name: "{{ k3s_system_name }}"
    enabled: yes
    masked: no
    state: restarted
